# Generated by Django 5.2.8 on 2026-01-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google OAuth user ID for social login.', max_length=255, null=True, unique=True, verbose_name='Google ID'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['google_id'], name='account_cus_google__0feb39_idx'),
        ),
    ]
