# Generated by Django 5.2.8 on 2026-02-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customer_no_template',
            field=models.CharField(blank=True, default='{userId}', help_text='Python str.format template that builds the customer_no sent to Digiflazz. Keys must match field "key" values in input_fields. Examples: "{userId}{serverId}" (Games w/ server), "{userId}" (Games ID only), "{phoneNumber}" (Pulsa/Data), "{customerNo}" (PLN/PDAM/BPJS/etc), "{noIdentitas},{noRangka}" (SAMSAT), "" (no input needed).', max_length=200, verbose_name='Customer No Template'),
        ),
    ]
