# Generated by Django 5.2.8 on 2026-01-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='icon',
            field=models.ImageField(blank=True, upload_to='payment_methods/icons/', verbose_name='Icon'),
        ),
    ]
