# Generated by Django 5.2.8 on 2026-01-29 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_paymentmethod_icon'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentmethod',
            name='unique_payment_method_type_bank',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='bank',
        ),
    ]
