# Generated by Django 5.2.8 on 2026-02-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_paymentmethod_unique_payment_method_type_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='is_validation_item',
            field=models.BooleanField(default=False, help_text="Items used for validation (e.g., 'Cek Username') - hidden from public listings", verbose_name='Is Validation Item'),
        ),
    ]
