# Generated by Django 5.2.8 on 2026-02-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productitem_is_validation_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Payment URL'),
        ),
    ]
