# Generated by Django 5.2.8 on 2026-02-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_payment_payment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='deeplink_url',
            field=models.CharField(blank=True, help_text='Deep link for e-wallets', max_length=500, null=True, verbose_name='Deep link URL'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='qris_string',
            field=models.TextField(blank=True, help_text='QRIS payment string (for qris)', null=True, verbose_name='QRIS String'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='redirect_url',
            field=models.CharField(blank=True, help_text='Redirect URL for credit card', max_length=500, null=True, verbose_name='Redirect URL'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='va_number',
            field=models.CharField(blank=True, help_text='Virtual Account number (for bank_transfer)', max_length=100, null=True, verbose_name='VA Number'),
        ),
    ]
