# Generated by Django 5.2.8 on 2026-02-03 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_payment_deeplink_url_alter_payment_qris_string_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigiflazzAccountCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref_id', models.CharField(help_text='Validation reference ID (CHECK-* or MLCHECK-*)', max_length=100, unique=True, verbose_name='Reference ID')),
                ('sku_code', models.CharField(help_text='Digiflazz SKU code used for validation', max_length=100, verbose_name='SKU Code')),
                ('customer_no', models.CharField(help_text='Game ID / phone number being validated', max_length=100, verbose_name='Customer No')),
                ('user_id', models.CharField(blank=True, help_text='User ID portion (for games with separate user/server)', max_length=50, verbose_name='User ID')),
                ('server_id', models.CharField(blank=True, help_text='Server ID portion (for games like Mobile Legends)', max_length=50, verbose_name='Server ID')),
                ('is_valid', models.BooleanField(default=False, help_text='Whether the account was found and validated', verbose_name='Is Valid')),
                ('account_name', models.CharField(blank=True, help_text='Account name returned by Digiflazz (SN field)', max_length=255, verbose_name='Account Name')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUKSES', 'Success'), ('GAGAL', 'Failed')], default='PENDING', max_length=10, verbose_name='Status')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('rc', models.CharField(blank=True, max_length=10, verbose_name='Response Code')),
                ('response_data', models.JSONField(blank=True, help_text='Full response from Digiflazz create_transaction API', null=True, verbose_name='Response Data')),
                ('webhook_data', models.JSONField(blank=True, help_text='Webhook callback data (if received)', null=True, verbose_name='Webhook Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_checks', to='main.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Digiflazz Account Check',
                'verbose_name_plural': 'Digiflazz Account Checks',
                'db_table': 'digiflazz_account_checks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ref_id'], name='digiflazz_a_ref_id_02e0c0_idx'), models.Index(fields=['customer_no'], name='digiflazz_a_custome_e812d1_idx'), models.Index(fields=['is_valid'], name='digiflazz_a_is_vali_e4820b_idx'), models.Index(fields=['created_at'], name='digiflazz_a_created_db1ffa_idx'), models.Index(fields=['product', 'created_at'], name='digiflazz_a_product_7dfa03_idx')],
            },
        ),
    ]
