# Generated by Django 5.2.8 on 2026-02-04 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_digiflazzaccountcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='order',
            field=models.ForeignKey(blank=True, help_text='The order this rating is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_rating', to='main.order', verbose_name='Order'),
        ),
    ]
