import "@/styles/globals.css";

import { type Metadata } from "next";
import { IBM_Plex_Sans_Condensed } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
  title: "PPOB App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

// FONT: IBM PLEX SANS CONDENSED
const ibmPlex = IBM_Plex_Sans_Condensed({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-ibm-condensed",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={ibmPlex.variable}>
      <body className="font-ibm">
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
